version: "v3.0"
name: Basic, 1 block YAML file example.
semaphore_image: standard
blocks:
# Is this a valid comment?
# Yes it is!
 - name: This is Block
   build:
      jobs:
        - name: "job name"
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - env
        - name: Job 2 from 1st build block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - env
        - name: Job 3 from 1st build block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - env
        - name: Job 4 from 1st build block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - env
        - name: Job 5 from 1st build block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - env
        - name: Job 6 from 1st build block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - env
 - name: Heyo This is another Block
   build:
      jobs:
        - name: Job 1 from 2nd build block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - env
        - name: Job 2 from 2nd build block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - env
